builders:
  header_generator:
    import: "package:umbrella_generator/builder.dart"
    builder_factories: ["headerGeneratorBuilder"]
    build_extensions: {".dart": [".header.dart"]}
    auto_apply: dependents
    build_to: source