name: umbrella_generator
description: A new Flutter package.
version: 1.0.0
homepage: https://github.com/Supernova-Studio/umbrella

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  build: ^1.6.3
  source_gen: ^0.9.10+3
  glob: ^2.0.0

  umbrella_annotation: ^1.0.0

dev_dependencies:
  build_test: ^1.3.7
  build_runner: ^1.11.5
  test: ^1.16.5


