name: umbrella_generator
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  glob: ^1.2.0

  umbrella_annotation:
    path: ./annotation

dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0


