name: umbrella_generator
description: Generator for umbrella_annotation.
version: 1.0.1
homepage: https://github.com/Supernova-Studio/umbrella

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  glob: ^2.0.0

  umbrella_annotation: ^1.0.1

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^1.11.5
  test: ^1.16.8


