name: umbrella_generator
description: A new Flutter package.
version: 0.0.3
homepage: https://github.com/Supernova-Studio/umbrella

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  build: '>=1.2.2 <2.0.0'
  source_gen: ^0.9.5
  glob: ^1.2.0

  umbrella_annotation: ^0.0.3

dev_dependencies:
  build_test: ^1.0.0
  build_runner: '>=1.8.0 <2.0.0'
  test: ^1.0.0


